language: node_js

node_js:
  - "node"   # Latest stable Node.js release
  - "lts/*"  # Latest LTS Node.js release

matrix:
  fast_finish: true

install:
  - yarn install

script:
  - echo -e "$(curl --silent https://raw.githubusercontent.com/FantasticFiasco/logo/master/logo.ansi)"
  - if [ "$TRAVIS_NODE_VERSION" == "node" ]; then yarn coverage; fi
  - if [ "$TRAVIS_NODE_VERSION" != "node" ]; then yarn test; fi
  - yarn lint

deploy:
  - provider: npm
    email: mattias.kindborg@gmail.com
    api_key:
      secure: ebbhOYR+0VjYiAQIBVmvTa12AFsQzKoUJslLK7lkp23MvrkC9aXlc3Rqdzk20X1rJGNsoALWIumgmjxXypxfSJ51Y/i+o3bGGjulIggmblpixa+OGLRxnR30r9k6PT9W8k2LIJyC5kY1CPWpTpUtkK6aj8TZ4B5x6Z8nWUciI3JFOcM7ZitUg/Dpq/h8tSTvS0cQWQecFaSmmRPosjdsLfl7qDPMEoqs6lAxZRbXy6rTrXoqjhRMSlGU+G7yLGiGpiSz7stpmy/Nz6ByEebHEkocwy8thPCK2iBKI9AoKO8ZM3bVDVEtq+C9cHjOWT6D99KDARZWAVdT+dsJNIaAQqPEwaRire1OswYc2WzYRVKJo0ioh8NxbNFk3jTEweKOdIN6k7jhWOPk0rgCW30z7/HhzXz1s7HJgVPVyjR6wHXDT9G2wdr/cVCsr3d3hwSa6A4awecAi9/Oep0Nd7t4M2+On3hliWsGIz4wW1lJP62GK5/VPEvZxejy498IaXiXA/KMQZVuMG+sc9Ge2LpHWjdxSwKAKl3ZiZDoTWaUabs9nmqACNKOHZC6zYam5qSdoMZUVX79fZmlmSyIC02SUgnSTh2M7poxpVVnirIDF51aPu94t6L9z5UhquFs6L4SiWyxM/XEJxmvKmIXou1Uj/X3/MSpoUcymPVmdsb1HP0=
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    name: Release $TRAVIS_TAG
    api_key:
      secure: et0/dc7d3cFGza0AnHLkLZ0IGqx/+NOqoNUnIlkd46Y7rhAX5sO3hbZn5tKnoiXXJf0FUXGeeymYyVf8jQN5+KVY6TbkBg/9e6haNzHrj9QcRRpRlXzoQeGgc6OitGSEPgx8Tbgx+rEl6O24Nfd1sVAgJlPh3+7d+/2jptc9nHv8YcvP/4S8upTAC0i+GqmAQsB7mNWzBQhIQuptOARqMpFFKlr0wYePsTWidkXqzsDgwl+qyY9crGMsI1zaBHOuZtdW8Kc0vJINkPtQA5y9+bC2zy5AcamDcqOXd9DxRDHbAas41Ky/5ggGrwXG2SNbk4NpSbCr199xFM4drkPoZTCk3RLJQWc1P8Ch9bRq3qwyJvKVxgcXjPAg4Bgzkat7ns+oDD24q9RcNr7VJeD9ubPchDT98LFkSd6Fj9HeLsM2l9JQSjd8pQTDuIIBFLEWSXOcGjzdqDON5XP5GEDIwsnA72MoC/TVUM0xVbOQ4HZ+vrbwfFEezu5mvVEY+4q5NxX2eAhR4KMWdda3s/yW7G2VOwOkWJqrv5+uKzFZMVw8fEBlPJOs1a8kqlb1MIEnQUJzItUI6H7DOBNycO56RICDzEmA0MAXUxmDloau5B6Q50whEK6X28spXiu/fRJ+7HtVBcGzDzYA04ksw52VJ9aHVIi4BezDsKzMXV/qDO4=
    on:
      tags: true
